// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `doc_kind_from_ext`, `load_index`, `new_id`, `now_secs`, `rand_u32`, `save_index`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`, `from`

Future<List<DocumentEntry>> listDocuments({required String dir}) =>
    RustLib.instance.api.crateApiDocumentsListDocuments(dir: dir);

Future<DocumentEntry> createDocumentEntry(
        {required String dir, required String name, required String ext}) =>
    RustLib.instance.api
        .crateApiDocumentsCreateDocumentEntry(dir: dir, name: name, ext: ext);

Future<void> renameDocumentEntry(
        {required String dir, required String id, required String newName}) =>
    RustLib.instance.api.crateApiDocumentsRenameDocumentEntry(
        dir: dir, id: id, newName: newName);

Future<bool> togglePinDocument({required String dir, required String id}) =>
    RustLib.instance.api.crateApiDocumentsTogglePinDocument(dir: dir, id: id);

Future<void> deleteDocumentEntry({required String dir, required String id}) =>
    RustLib.instance.api.crateApiDocumentsDeleteDocumentEntry(dir: dir, id: id);

class DocumentEntry {
  final String id;
  final String name;
  final String ext;
  final bool pinned;
  final BigInt createdAt;
  final BigInt updatedAt;

  const DocumentEntry({
    required this.id,
    required this.name,
    required this.ext,
    required this.pinned,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      ext.hashCode ^
      pinned.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          ext == other.ext &&
          pinned == other.pinned &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
