// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clean_name`, `load`, `new_id`, `now_secs`, `rand_u32`, `save`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`

Future<List<FolderEntry>> listFolders(
        {required String dir, required String ext}) =>
    RustLib.instance.api.crateApiFoldersListFolders(dir: dir, ext: ext);

Future<List<DocumentFolderLink>> listFolderLinks({required String dir}) =>
    RustLib.instance.api.crateApiFoldersListFolderLinks(dir: dir);

Future<FolderEntry> createFolder(
        {required String dir, required String name, required String ext}) =>
    RustLib.instance.api
        .crateApiFoldersCreateFolder(dir: dir, name: name, ext: ext);

Future<void> renameFolder(
        {required String dir, required String id, required String newName}) =>
    RustLib.instance.api
        .crateApiFoldersRenameFolder(dir: dir, id: id, newName: newName);

Future<void> deleteFolder({required String dir, required String id}) =>
    RustLib.instance.api.crateApiFoldersDeleteFolder(dir: dir, id: id);

Future<void> moveDocumentToFolder(
        {required String dir, required String documentId, String? folderId}) =>
    RustLib.instance.api.crateApiFoldersMoveDocumentToFolder(
        dir: dir, documentId: documentId, folderId: folderId);

class DocumentFolderLink {
  final String documentId;
  final String folderId;

  const DocumentFolderLink({
    required this.documentId,
    required this.folderId,
  });

  @override
  int get hashCode => documentId.hashCode ^ folderId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentFolderLink &&
          runtimeType == other.runtimeType &&
          documentId == other.documentId &&
          folderId == other.folderId;
}

class FolderEntry {
  final String id;
  final String name;
  final String ext;
  final BigInt createdAt;
  final BigInt updatedAt;

  const FolderEntry({
    required this.id,
    required this.name,
    required this.ext,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      ext.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FolderEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          ext == other.ext &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
