// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_accent`, `default_theme_mode`, `sanitize`, `settings_path`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

Future<AppSettings> loadSettings({required String dir}) =>
    RustLib.instance.api.crateApiSettingsLoadSettings(dir: dir);

Future<void> saveSettings(
        {required String dir, required AppSettings settings}) =>
    RustLib.instance.api
        .crateApiSettingsSaveSettings(dir: dir, settings: settings);

class AppSettings {
  final String themeMode;
  final String accent;

  const AppSettings({
    required this.themeMode,
    required this.accent,
  });

  static Future<AppSettings> default_() =>
      RustLib.instance.api.crateApiSettingsAppSettingsDefault();

  @override
  int get hashCode => themeMode.hashCode ^ accent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettings &&
          runtimeType == other.runtimeType &&
          themeMode == other.themeMode &&
          accent == other.accent;
}
