// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'io.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> appVersion() => RustLib.instance.api.crateApiAppVersion();

Future<void> createDocument({required String path, required DocKind kind}) =>
    RustLib.instance.api.crateApiCreateDocument(path: path, kind: kind);

Future<DocKind> readDocumentKind({required String path}) =>
    RustLib.instance.api.crateApiReadDocumentKind(path: path);
