// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/documents.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'io.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 884923406;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'collecti_native',
    ioDirectory: 'native/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiAppVersion();

  Future<void> crateApiCreateDocument(
      {required String path, required DocKind kind});

  Future<DocumentEntry> crateApiDocumentsCreateDocumentEntry(
      {required String dir, required String name, required String ext});

  Future<void> crateApiDocumentsDeleteDocumentEntry(
      {required String dir, required String id});

  Future<String> crateApiGetCellInput(
      {required int sheetIndex, required int row, required int col});

  Future<List<CellSnapshot>> crateApiGetSheetSnapshot(
      {required int sheetIndex});

  Future<List<DocumentEntry>> crateApiDocumentsListDocuments(
      {required String dir});

  Future<void> crateApiOpenWorkbook({required String path});

  Future<DocKind> crateApiReadDocumentKind({required String path});

  Future<void> crateApiDocumentsRenameDocumentEntry(
      {required String dir, required String id, required String newName});

  Future<void> crateApiSaveWorkbook({required String path});

  Future<List<CellSnapshot>> crateApiSetCellInput(
      {required int sheetIndex,
      required int row,
      required int col,
      required String input});

  Future<bool> crateApiDocumentsTogglePinDocument(
      {required String dir, required String id});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiAppVersion() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiAppVersionConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAppVersionConstMeta => const TaskConstMeta(
        debugName: "app_version",
        argNames: [],
      );

  @override
  Future<void> crateApiCreateDocument(
      {required String path, required DocKind kind}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_doc_kind(kind, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCreateDocumentConstMeta,
      argValues: [path, kind],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCreateDocumentConstMeta => const TaskConstMeta(
        debugName: "create_document",
        argNames: ["path", "kind"],
      );

  @override
  Future<DocumentEntry> crateApiDocumentsCreateDocumentEntry(
      {required String dir, required String name, required String ext}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dir, serializer);
        sse_encode_String(name, serializer);
        sse_encode_String(ext, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_document_entry,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDocumentsCreateDocumentEntryConstMeta,
      argValues: [dir, name, ext],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDocumentsCreateDocumentEntryConstMeta =>
      const TaskConstMeta(
        debugName: "create_document_entry",
        argNames: ["dir", "name", "ext"],
      );

  @override
  Future<void> crateApiDocumentsDeleteDocumentEntry(
      {required String dir, required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dir, serializer);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDocumentsDeleteDocumentEntryConstMeta,
      argValues: [dir, id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDocumentsDeleteDocumentEntryConstMeta =>
      const TaskConstMeta(
        debugName: "delete_document_entry",
        argNames: ["dir", "id"],
      );

  @override
  Future<String> crateApiGetCellInput(
      {required int sheetIndex, required int row, required int col}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_32(sheetIndex, serializer);
        sse_encode_u_32(row, serializer);
        sse_encode_u_32(col, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetCellInputConstMeta,
      argValues: [sheetIndex, row, col],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetCellInputConstMeta => const TaskConstMeta(
        debugName: "get_cell_input",
        argNames: ["sheetIndex", "row", "col"],
      );

  @override
  Future<List<CellSnapshot>> crateApiGetSheetSnapshot(
      {required int sheetIndex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_32(sheetIndex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_cell_snapshot,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetSheetSnapshotConstMeta,
      argValues: [sheetIndex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetSheetSnapshotConstMeta => const TaskConstMeta(
        debugName: "get_sheet_snapshot",
        argNames: ["sheetIndex"],
      );

  @override
  Future<List<DocumentEntry>> crateApiDocumentsListDocuments(
      {required String dir}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dir, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_document_entry,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDocumentsListDocumentsConstMeta,
      argValues: [dir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDocumentsListDocumentsConstMeta =>
      const TaskConstMeta(
        debugName: "list_documents",
        argNames: ["dir"],
      );

  @override
  Future<void> crateApiOpenWorkbook({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiOpenWorkbookConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOpenWorkbookConstMeta => const TaskConstMeta(
        debugName: "open_workbook",
        argNames: ["path"],
      );

  @override
  Future<DocKind> crateApiReadDocumentKind({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_doc_kind,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiReadDocumentKindConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiReadDocumentKindConstMeta => const TaskConstMeta(
        debugName: "read_document_kind",
        argNames: ["path"],
      );

  @override
  Future<void> crateApiDocumentsRenameDocumentEntry(
      {required String dir, required String id, required String newName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dir, serializer);
        sse_encode_String(id, serializer);
        sse_encode_String(newName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDocumentsRenameDocumentEntryConstMeta,
      argValues: [dir, id, newName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDocumentsRenameDocumentEntryConstMeta =>
      const TaskConstMeta(
        debugName: "rename_document_entry",
        argNames: ["dir", "id", "newName"],
      );

  @override
  Future<void> crateApiSaveWorkbook({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSaveWorkbookConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSaveWorkbookConstMeta => const TaskConstMeta(
        debugName: "save_workbook",
        argNames: ["path"],
      );

  @override
  Future<List<CellSnapshot>> crateApiSetCellInput(
      {required int sheetIndex,
      required int row,
      required int col,
      required String input}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_32(sheetIndex, serializer);
        sse_encode_u_32(row, serializer);
        sse_encode_u_32(col, serializer);
        sse_encode_String(input, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_cell_snapshot,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSetCellInputConstMeta,
      argValues: [sheetIndex, row, col, input],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSetCellInputConstMeta => const TaskConstMeta(
        debugName: "set_cell_input",
        argNames: ["sheetIndex", "row", "col", "input"],
      );

  @override
  Future<bool> crateApiDocumentsTogglePinDocument(
      {required String dir, required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dir, serializer);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDocumentsTogglePinDocumentConstMeta,
      argValues: [dir, id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDocumentsTogglePinDocumentConstMeta =>
      const TaskConstMeta(
        debugName: "toggle_pin_document",
        argNames: ["dir", "id"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CellSnapshot dco_decode_cell_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CellSnapshot(
      row: dco_decode_u_32(arr[0]),
      col: dco_decode_u_32(arr[1]),
      display: dco_decode_String(arr[2]),
      isError: dco_decode_bool(arr[3]),
    );
  }

  @protected
  DocKind dco_decode_doc_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DocKind.values[raw as int];
  }

  @protected
  DocumentEntry dco_decode_document_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return DocumentEntry(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      ext: dco_decode_String(arr[2]),
      pinned: dco_decode_bool(arr[3]),
      createdAt: dco_decode_u_64(arr[4]),
      updatedAt: dco_decode_u_64(arr[5]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<CellSnapshot> dco_decode_list_cell_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_cell_snapshot).toList();
  }

  @protected
  List<DocumentEntry> dco_decode_list_document_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_document_entry).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CellSnapshot sse_decode_cell_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_row = sse_decode_u_32(deserializer);
    var var_col = sse_decode_u_32(deserializer);
    var var_display = sse_decode_String(deserializer);
    var var_isError = sse_decode_bool(deserializer);
    return CellSnapshot(
        row: var_row, col: var_col, display: var_display, isError: var_isError);
  }

  @protected
  DocKind sse_decode_doc_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DocKind.values[inner];
  }

  @protected
  DocumentEntry sse_decode_document_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_ext = sse_decode_String(deserializer);
    var var_pinned = sse_decode_bool(deserializer);
    var var_createdAt = sse_decode_u_64(deserializer);
    var var_updatedAt = sse_decode_u_64(deserializer);
    return DocumentEntry(
        id: var_id,
        name: var_name,
        ext: var_ext,
        pinned: var_pinned,
        createdAt: var_createdAt,
        updatedAt: var_updatedAt);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<CellSnapshot> sse_decode_list_cell_snapshot(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CellSnapshot>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_cell_snapshot(deserializer));
    }
    return ans_;
  }

  @protected
  List<DocumentEntry> sse_decode_list_document_entry(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DocumentEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_document_entry(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_cell_snapshot(CellSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.row, serializer);
    sse_encode_u_32(self.col, serializer);
    sse_encode_String(self.display, serializer);
    sse_encode_bool(self.isError, serializer);
  }

  @protected
  void sse_encode_doc_kind(DocKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_document_entry(DocumentEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.ext, serializer);
    sse_encode_bool(self.pinned, serializer);
    sse_encode_u_64(self.createdAt, serializer);
    sse_encode_u_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_cell_snapshot(
      List<CellSnapshot> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_cell_snapshot(item, serializer);
    }
  }

  @protected
  void sse_encode_list_document_entry(
      List<DocumentEntry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_document_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
