// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'api/documents.dart';
import 'api/folders.dart';
import 'api/settings.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'io.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppSettings dco_decode_app_settings(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AppSettings dco_decode_box_autoadd_app_settings(dynamic raw);

  @protected
  CellSnapshot dco_decode_cell_snapshot(dynamic raw);

  @protected
  DocKind dco_decode_doc_kind(dynamic raw);

  @protected
  DocumentEntry dco_decode_document_entry(dynamic raw);

  @protected
  DocumentFolderLink dco_decode_document_folder_link(dynamic raw);

  @protected
  FolderEntry dco_decode_folder_entry(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<CellSnapshot> dco_decode_list_cell_snapshot(dynamic raw);

  @protected
  List<DocumentEntry> dco_decode_list_document_entry(dynamic raw);

  @protected
  List<DocumentFolderLink> dco_decode_list_document_folder_link(dynamic raw);

  @protected
  List<FolderEntry> dco_decode_list_folder_entry(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_app_settings(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_box_autoadd_app_settings(SseDeserializer deserializer);

  @protected
  CellSnapshot sse_decode_cell_snapshot(SseDeserializer deserializer);

  @protected
  DocKind sse_decode_doc_kind(SseDeserializer deserializer);

  @protected
  DocumentEntry sse_decode_document_entry(SseDeserializer deserializer);

  @protected
  DocumentFolderLink sse_decode_document_folder_link(
      SseDeserializer deserializer);

  @protected
  FolderEntry sse_decode_folder_entry(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<CellSnapshot> sse_decode_list_cell_snapshot(
      SseDeserializer deserializer);

  @protected
  List<DocumentEntry> sse_decode_list_document_entry(
      SseDeserializer deserializer);

  @protected
  List<DocumentFolderLink> sse_decode_list_document_folder_link(
      SseDeserializer deserializer);

  @protected
  List<FolderEntry> sse_decode_list_folder_entry(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_settings(AppSettings self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_app_settings(
      AppSettings self, SseSerializer serializer);

  @protected
  void sse_encode_cell_snapshot(CellSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_doc_kind(DocKind self, SseSerializer serializer);

  @protected
  void sse_encode_document_entry(DocumentEntry self, SseSerializer serializer);

  @protected
  void sse_encode_document_folder_link(
      DocumentFolderLink self, SseSerializer serializer);

  @protected
  void sse_encode_folder_entry(FolderEntry self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_cell_snapshot(
      List<CellSnapshot> self, SseSerializer serializer);

  @protected
  void sse_encode_list_document_entry(
      List<DocumentEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_document_folder_link(
      List<DocumentFolderLink> self, SseSerializer serializer);

  @protected
  void sse_encode_list_folder_entry(
      List<FolderEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
