// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class DocumentEntry {
  final String id;
  final String name;
  final String ext;
  final bool pinned;
  final BigInt createdAt;
  final BigInt updatedAt;

  const DocumentEntry({
    required this.id,
    required this.name,
    required this.ext,
    required this.pinned,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      ext.hashCode ^
      pinned.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          ext == other.ext &&
          pinned == other.pinned &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
